void create_db(char a);
void *add_student(int student_number, char* first_name);
void *add_teacher(int teacher_number, char* first_name);
void *add_course(int course_number, char* course_name, int semester_number);
void *add_assignment(int teacher_number, int course_number);
void *add_enrolment(int student_number, int course_number);
void *enrol_student(int student_number, int course_number);
void *assign_teacher(int teacher_number, int course_number);
void get_courses_by_student_number(int student_number);
void get_courses_by_teacher_number(int teacher_number);
void get_students_by_course_number(int course_number);
void get_teachers_by_student_number(int student_number);
int remove_student(int student_number);
void print_student_list();
void print_teacher_list();
void print_course_list();
void print_assignment_list();
void print_enrolment_list();